
title: STARTGUIDE.jp
email: ituyama01@stopover.co.jp

baseurl: / # the subpath of your site, e.g. /blog
url: https://startguide.jp/ # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  startguide

# Build settings
theme: default
plugins:
  - jekyll-feed
  - jekyll-algolia
permalink: /:month/:day/:minute

algolia:
  application_id: BPQTJ88369
  index_name: startguide
   search_only_api_key: 8d099779debe42c51a53fc439f19ff10
