
title: CoderDojoSannomaru
email: sannomaru@coderdojo.com


url: "https://www.startguide.jp "
baseurl : /
# Build settings
layout: default
plugins:
  - jekyll-feed

permalink: /:categories/:month/:day/:minute
gist:
  noscript: false
