
title: STARTGUIDE.jp
email: ituyama01@stopover.co.jp

baseurl: / # the subpath of your site, e.g. /blog
url: https://startguide.jp/ # the base hostname & protocol for your site, e.g. http://example.com




# Build settings
theme: startguide
plugins:
  - jekyll-feed

permalink: /:month/:day/:minute

